#!/usr/bin/php
<?php
require("a2.php");
//$usage = "Usage: $argv[0] ActorName";
$db = dbConnect(DB_CONNECTION);
$start_name = $argv[1];
$start_degree = $argv[2];
$end_degree = $argv[3];


$start_name_id = actor_name_to_id($start_name);


// first degree
$q = "create or replace view degree_one as select zero.actor_id as actor_zero, one.movie_id as movie_zero_one, one.actor_id as actor_one from acting as zero join acting as one on zero.movie_id = one.movie_id where zero.actor_id = ".$start_name_id." and zero.actor_id != one.actor_id";
$r = dbQuery($db,$q);
$q = "select * from degree_one";
$r = dbQuery($db, $q);


//second degree

$q = "create or replace view degree_two as select degree_one.*, a1.movie_id as movie_one_two, a2.actor_id as actor_two from degree_one join acting as a1 on a1.actor_id = degree_one.actor_one join acting as a2 on a2.movie_id = a1.movie_id where  a1.movie_id != movie_zero_one";
$r = dbQuery($db, $q);



//third degree
$q = "create or replace view degree_three as select degree_two.*, a1.movie_id as movie_two_three, a2.actor_id as actor_three from degree_two join acting as a1 on a1.actor_id = degree_two.actor_two join acting as a2 on a2.movie_id = a1.movie_id where  a1.movie_id != movie_one_two";
$r = dbQuery($db, $q);


//fourth degree
$q = "create or replace view degree_four as select degree_three.*, a1.movie_id as movie_three_four, a2.actor_id as actor_four from degree_three join acting as a1 on a1.actor_id = degree_three.actor_three join acting as a2 on a2.movie_id = a1.movie_id where  a1.movie_id != movie_two_three";
$r = dbQuery($db, $q);


//fifth degree
$q = "create or replace view degree_five as select degree_four.*, a1.movie_id as movie_four_five, a2.actor_id as actor_five from degree_four join acting as a1 on a1.actor_id = degree_four.actor_four join acting as a2 on a2.movie_id = a1.movie_id where  a1.movie_id != movie_three_four";
$r = dbQuery($db, $q);




//sixth degree
$q = "create or replace view degree_six as select degree_five.*, a1.movie_id as movie_five_six, a2.actor_id as actor_six from degree_five join acting as a1 on a1.actor_id = degree_five.actor_five join acting as a2 on a2.movie_id = a1.movie_id where  a1.movie_id != movie_four_five";
$r = dbQuery($db, $q);


//find degree zero actor
$degree[0][0] = $start_name_id;
//find all degree one actors
$q = "select distinct actor_one from degree_one where actor_one != actor_zero";
$r = dbQuery($db, $q);
while($t = dbNext($r)){
    $degree[1][]=$t[0];
}
//find all degree two actors










function actor_name_to_id($name){
    $name = str_replace("'","''",$name);
    $db = dbConnect(DB_CONNECTION);
    $name = strtolower($name);
    //echo "name is $name\n";
    $q = "select id from actor where lower(name) = '".$name."'";
    //echo "$q\n";
    $r = dbQuery($db, $q);
    $t = dbNext($r);
    $id = $t[0];
    
    return $id;
}
function actor_id_to_name($id){
    $db = dbConnect(DB_CONNECTION);
    $q = "select name from actor where id = ".$id;
    $r = dbQuery($db, $q);
    $t = dbNext($r);
    $name = $t[0];
    $name = strtolower($name);
    return $name;
}
function movie_id_to_name($id){
    $db = dbConnect(DB_CONNECTION);
    $q = "select title from movie where id = ".$id;
    $r = dbQuery($db, $q);
    $t = dbNext($r);
    $name = $t[0];
    //$name = strtolower($name);
    return $name;
}
function to_capital_name($name){
    $db = dbConnect(DB_CONNECTION);
    $id = actor_name_to_id($name);
    $q = "select name from actor where id = ".$id;
    $r = dbQuery($db, $q);
    $t = dbNext($r);
    $name = $t[0];
    return $name;
}
function get_movie_time($movie_name){
    $movie_name = str_replace("'","''",$movie_name);
    $db = dbConnect(DB_CONNECTION);
    $q = "select year from movie where title = '".$movie_name."'";
    $r = dbQuery($db,$q);
    $t = dbNext($r);
    $year = $t[0];
    return $year; 
}


?>