#!/usr/bin/php
<?php
   $array[0]=0;
   $array[1]=1;
   $array[2]=2;
   $array[3]=3;

   unset($array[1]);
   foreach($array as $num){
       echo "$num\n";
   }
?>

1, chris evans <=> Fantastic 4: Rise of the Silver Surfer <=> andre braugher; andre braugher <=> City of Angels <=> nicolas cage; nicolas cage <=> Kiss of Death <=> michael rapaport; michael rapaport <=> Lucky Numbers <=> michael moore; michael moore <=> Sicko <=> bill clinton; 
2, chris evans <=> Fantastic 4: Rise of the Silver Surfer <=> andre braugher; andre braugher <=> City of Angels <=> nicolas cage; nicolas cage <=> Kiss of Death <=> michael rapaport; michael rapaport <=> Lucky Numbers <=> michael moore; michael moore <=> Bowling for Columbine <=> bill clinton; 
3, chris evans <=> The Iceman <=> james franco; james franco <=> In the Valley of Elah <=> charlize theron; charlize theron <=> Men of Honor <=> michael rapaport; michael rapaport <=> Lucky Numbers <=> michael moore; michael moore <=> Sicko <=> bill clinton; 
4, chris evans <=> The Iceman <=> james franco; james franco <=> In the Valley of Elah <=> charlize theron; charlize theron <=> Men of Honor <=> michael rapaport; michael rapaport <=> Lucky Numbers <=> michael moore; michael moore <=> Bowling for Columbine <=> bill clinton; 
5, chris evans <=> London <=> jason statham; jason statham <=> The Italian Job <=> charlize theron; charlize theron <=> Men of Honor <=> michael rapaport; michael rapaport <=> Lucky Numbers <=> michael moore; michael moore <=> Sicko <=> bill clinton; 
6, chris evans <=> London <=> jason statham; jason statham <=> The Italian Job <=> charlize theron; charlize theron <=> Men of Honor <=> michael rapaport; michael rapaport <=> Lucky Numbers <=> michael moore; michael moore <=> Bowling for Columbine <=> bill clinton; 
7, chris evans <=> Street Kings <=> keanu reeves; keanu reeves <=> The Devil's Advocate <=> charlize theron; charlize theron <=> Men of Honor <=> michael rapaport; michael rapaport <=> Lucky Numbers <=> michael moore; michael moore <=> Sicko <=> bill clinton; 
8, chris evans <=> Street Kings <=> keanu reeves; keanu reeves <=> The Devil's Advocate <=> charlize theron; charlize theron <=> Men of Honor <=> michael rapaport; michael rapaport <=> Lucky Numbers <=> michael moore; michael moore <=> Bowling for Columbine <=> bill clinton; 
9, chris evans <=> Street Kings <=> keanu reeves; keanu reeves <=> Sweet November <=> charlize theron; charlize theron <=> Men of Honor <=> michael rapaport; michael rapaport <=> Lucky Numbers <=> michael moore; michael moore <=> Sicko <=> bill clinton; 
10, chris evans <=> Street Kings <=> keanu reeves; keanu reeves <=> Sweet November <=> charlize theron; charlize theron <=> Men of Honor <=> michael rapaport; michael rapaport <=> Lucky Numbers <=> michael moore; michael moore <=> Bowling for Columbine <=> bill clinton; 
11, chris evans <=> The Iceman <=> james franco; james franco <=> City by the Sea <=> robert de niro; robert de niro <=> Men of Honor <=> michael rapaport; michael rapaport <=> Lucky Numbers <=> michael moore; michael moore <=> Sicko <=> bill clinton; 
12, chris evans <=> The Iceman <=> james franco; james franco <=> City by the Sea <=> robert de niro; robert de niro <=> Men of Honor <=> michael rapaport; michael rapaport <=> Lucky Numbers <=> michael moore; michael moore <=> Bowling for Columbine <=> bill clinton; 
13, chris evans <=> London <=> jason statham; jason statham <=> Killer Elite <=> robert de niro; robert de niro <=> Men of Honor <=> michael rapaport; michael rapaport <=> Lucky Numbers <=> michael moore; michael moore <=> Sicko <=> bill clinton; 
14, chris evans <=> London <=> jason statham; jason statham <=> Killer Elite <=> robert de niro; robert de niro <=> Men of Honor <=> michael rapaport; michael rapaport <=> Lucky Numbers <=> michael moore; michael moore <=> Bowling for Columbine <=> bill clinton; 
15, chris evans <=> TMNT <=> mako; mako <=> Seven Years in Tibet <=> brad pitt; brad pitt <=> True Romance <=> michael rapaport; michael rapaport <=> Lucky Numbers <=> michael moore; michael moore <=> Sicko <=> bill clinton; 
16, chris evans <=> TMNT <=> mako; mako <=> Seven Years in Tibet <=> brad pitt; brad pitt <=> True Romance <=> michael rapaport; michael rapaport <=> Lucky Numbers <=> michael moore; michael moore <=> Bowling for Columbine <=> bill clinton; 
17, chris evans <=> London <=> jason statham; jason statham <=> Snatch <=> brad pitt; brad pitt <=> True Romance <=> michael rapaport; michael rapaport <=> Lucky Numbers <=> michael moore; michael moore <=> Sicko <=> bill clinton; 
18, chris evans <=> London <=> jason statham; jason statham <=> Snatch <=> brad pitt; brad pitt <=> True Romance <=> michael rapaport; michael rapaport <=> Lucky Numbers <=> michael moore; michael moore <=> Bowling for Columbine <=> bill clinton; 
19, chris evans <=> Captain America: Civil War <=> scarlett johansson; scarlett johansson <=> Girl with a Pearl Earring <=> tom wilkinson; tom wilkinson <=> Little Boy <=> michael rapaport; michael rapaport <=> Lucky Numbers <=> michael moore; michael moore <=> Sicko <=> bill clinton; 
20, chris evans <=> Captain America: Civil War <=> scarlett johansson; scarlett johansson <=> Girl with a Pearl Earring <=> tom wilkinson; tom wilkinson <=> Little Boy <=> michael rapaport; michael rapaport <=> Lucky Numbers <=> michael moore; michael moore <=> Bowling for Columbine <=> bill clinton; 
21, chris evans <=> Captain America: The Winter Soldier <=> scarlett johansson; scarlett johansson <=> Girl with a Pearl Earring <=> tom wilkinson; tom wilkinson <=> Little Boy <=> michael rapaport; michael rapaport <=> Lucky Numbers <=> michael moore; michael moore <=> Sicko <=> bill clinton; 
22, chris evans <=> Captain America: The Winter Soldier <=> scarlett johansson; scarlett johansson <=> Girl with a Pearl Earring <=> tom wilkinson; tom wilkinson <=> Little Boy <=> michael rapaport; michael rapaport <=> Lucky Numbers <=> michael moore; michael moore <=> Bowling for Columbine <=> bill clinton; 
23, chris evans <=> London <=> jason statham; jason statham <=> Ghosts of Mars <=> natasha henstridge; natasha henstridge <=> Should've Been Romeo <=> michael rapaport; michael rapaport <=> Lucky Numbers <=> michael moore; michael moore <=> Sicko <=> bill clinton; 
24, chris evans <=> London <=> jason statham; jason statham <=> Ghosts of Mars <=> natasha henstridge; natasha henstridge <=> Should've Been Romeo <=> michael rapaport; michael rapaport <=> Lucky Numbers <=> michael moore; michael moore <=> Bowling for Columbine <=> bill clinton; 
25, chris evans <=> London <=> jason statham; jason statham <=> The Bank Job <=> saffron burrows; saffron burrows <=> Deep Blue Sea <=> michael rapaport; michael rapaport <=> Lucky Numbers <=> michael moore; michael moore <=> Sicko <=> bill clinton; 
26, chris evans <=> London <=> jason statham; jason statham <=> The Bank Job <=> saffron burrows; saffron burrows <=> Deep Blue Sea <=> michael rapaport; michael rapaport <=> Lucky Numbers <=> michael moore; michael moore <=> Bowling for Columbine <=> bill clinton; 
27, chris evans <=> Street Kings <=> noel gugliemi; noel gugliemi <=> Small Apartments <=> saffron burrows; saffron burrows <=> Deep Blue Sea <=> michael rapaport; michael rapaport <=> Lucky Numbers <=> michael moore; michael moore <=> Sicko <=> bill clinton; 
28, chris evans <=> Street Kings <=> noel gugliemi; noel gugliemi <=> Small Apartments <=> saffron burrows; saffron burrows <=> Deep Blue Sea <=> michael rapaport; michael rapaport <=> Lucky Numbers <=> michael moore; michael moore <=> Bowling for Columbine <=> bill clinton; 
29, chris evans <=> London <=> jason statham; jason statham <=> The Mechanic <=> tony goldwyn; tony goldwyn <=> The 6th Day <=> michael rapaport; michael rapaport <=> Lucky Numbers <=> michael moore; michael moore <=> Sicko <=> bill clinton; 
30, chris evans <=> London <=> jason statham; jason statham <=> The Mechanic <=> tony goldwyn; tony goldwyn <=> The 6th Day <=> michael rapaport; michael rapaport <=> Lucky Numbers <=> michael moore; michael moore <=> Bowling for Columbine <=> bill clinton; 
31, chris evans <=> Street Kings <=> keanu reeves; keanu reeves <=> 47 Ronin <=> cary-hiroyuki tagawa; cary-hiroyuki tagawa <=> Little Boy <=> michael rapaport; michael rapaport <=> Lucky Numbers <=> michael moore; michael moore <=> Sicko <=> bill clinton; 
32, chris evans <=> Street Kings <=> keanu reeves; keanu reeves <=> 47 Ronin <=> cary-hiroyuki tagawa; cary-hiroyuki tagawa <=> Little Boy <=> michael rapaport; michael rapaport <=> Lucky Numbers <=> michael moore; michael moore <=> Bowling for Columbine <=> bill clinton; 
33, chris evans <=> Street Kings <=> keanu reeves; keanu reeves <=> Bram Stoker's Dracula <=> gary oldman; gary oldman <=> True Romance <=> michael rapaport; michael rapaport <=> Lucky Numbers <=> michael moore; michael moore <=> Sicko <=> bill clinton; 
34, chris evans <=> Street Kings <=> keanu reeves; keanu reeves <=> Bram Stoker's Dracula <=> gary oldman; gary oldman <=> True Romance <=> michael rapaport; michael rapaport <=> Lucky Numbers <=> michael moore; michael moore <=> Bowling for Columbine <=> bill clinton; 
35, chris evans <=> Captain America: Civil War <=> robert downey jr.; robert downey jr. <=> Lucky You <=> robert duvall; robert duvall <=> The 6th Day <=> michael rapaport; michael rapaport <=> Lucky Numbers <=> michael moore; michael moore <=> Sicko <=> bill clinton; 
36, chris evans <=> Captain America: Civil War <=> robert downey jr.; robert downey jr. <=> Lucky You <=> robert duvall; robert duvall <=> The 6th Day <=> michael rapaport; michael rapaport <=> Lucky Numbers <=> michael moore; michael moore <=> Bowling for Columbine <=> bill clinton; 
37, chris evans <=> Captain America: Civil War <=> robert downey jr.; robert downey jr. <=> The Judge <=> robert duvall; robert duvall <=> The 6th Day <=> michael rapaport; michael rapaport <=> Lucky Numbers <=> michael moore; michael moore <=> Sicko <=> bill clinton; 
38, chris evans <=> Captain America: Civil War <=> robert downey jr.; robert downey jr. <=> The Judge <=> robert duvall; robert duvall <=> The 6th Day <=> michael rapaport; michael rapaport <=> Lucky Numbers <=> michael moore; michael moore <=> Bowling for Columbine <=> bill clinton; 
39, chris evans <=> Fantastic 4: Rise of the Silver Surfer <=> andre braugher; andre braugher <=> Get on the Bus <=> bernie mac; bernie mac <=> What's the Worst That Could Happen? <=> richard schiff; richard schiff <=> Lucky Numbers <=> michael moore; michael moore <=> Sicko <=> bill clinton; 
40, chris evans <=> Fantastic 4: Rise of the Silver Surfer <=> andre braugher; andre braugher <=> Get on the Bus <=> bernie mac; bernie mac <=> What's the Worst That Could Happen? <=> richard schiff; richard schiff <=> Lucky Numbers <=> michael moore; michael moore <=> Bowling for Columbine <=> bill clinton; 
41, chris evans <=> Sunshine <=> benedict wong; benedict wong <=> Dirty Pretty Things <=> sophie okonedo; sophie okonedo <=> Martian Child <=> richard schiff; richard schiff <=> Lucky Numbers <=> michael moore; michael moore <=> Sicko <=> bill clinton; 
42, chris evans <=> Sunshine <=> benedict wong; benedict wong <=> Dirty Pretty Things <=> sophie okonedo; sophie okonedo <=> Martian Child <=> richard schiff; richard schiff <=> Lucky Numbers <=> michael moore; michael moore <=> Bowling for Columbine <=> bill clinton; 
43, chris evans <=> The Losers <=> jason patric; jason patric <=> The Lost Boys <=> dianne wiest; dianne wiest <=> I Am Sam <=> richard schiff; richard schiff <=> Lucky Numbers <=> michael moore; michael moore <=> Sicko <=> bill clinton; 
44, chris evans <=> The Losers <=> jason patric; jason patric <=> The Lost Boys <=> dianne wiest; dianne wiest <=> I Am Sam <=> richard schiff; richard schiff <=> Lucky Numbers <=> michael moore; michael moore <=> Bowling for Columbine <=> bill clinton; 
45, chris evans <=> Street Kings <=> keanu reeves; keanu reeves <=> The Devil's Advocate <=> al pacino; al pacino <=> People I Know <=> richard schiff; richard schiff <=> Lucky Numbers <=> michael moore; michael moore <=> Sicko <=> bill clinton; 
46, chris evans <=> Street Kings <=> keanu reeves; keanu reeves <=> The Devil's Advocate <=> al pacino; al pacino <=> People I Know <=> richard schiff; richard schiff <=> Lucky Numbers <=> michael moore; michael moore <=> Bowling for Columbine <=> bill clinton; 
47, chris evans <=> Captain America: Civil War <=> robert downey jr.; robert downey jr. <=> Kiss Kiss Bang Bang <=> larry miller; larry miller <=> What's the Worst That Could Happen? <=> richard schiff; richard schiff <=> Lucky Numbers <=> michael moore; michael moore <=> Sicko <=> bill clinton; 
48, chris evans <=> Captain America: Civil War <=> robert downey jr.; robert downey jr. <=> Kiss Kiss Bang Bang <=> larry miller; larry miller <=> What's the Worst That Could Happen? <=> richard schiff; richard schiff <=> Lucky Numbers <=> michael moore; michael moore <=> Bowling for Columbine <=> bill clinton; 
49, chris evans <=> Captain America: Civil War <=> robert downey jr.; robert downey jr. <=> The Soloist <=> stephen root; stephen root <=> Imagine That <=> richard schiff; richard schiff <=> Lucky Numbers <=> michael moore; michael moore <=> Sicko <=> bill clinton; 
50, chris evans <=> Captain America: Civil War <=> robert downey jr.; robert downey jr. <=> The Soloist <=> stephen root; stephen root <=> Imagine That <=> richard schiff; richard schiff <=> Lucky Numbers <=> michael moore; michael moore <=> Bowling for Columbine <=> bill clinton; 
